Revert "miatoll: power: Add custom boost extension for scroll handling"
This reverts commit 38bb780268b98efa00c1c165e950667b27a67bb1.

endor/qcom/opensource/power/../../../../device/xiaomi/miatoll/power/mode-ext.cpp:56:13: error: use of undeclared identifier 'CHECK_HANDLE'
        if (CHECK_HANDLE(launch_handle)) {
            ^
vendor/qcom/opensource/power/../../../../device/xiaomi/miatoll/power/mode-ext.cpp:65:52: error: use of undeclared identifier 'VENDOR_HINT_FIRST_LAUNCH_BOOST'
        launch_handle = perf_hint_enable_with_type(VENDOR_HINT_FIRST_LAUNCH_BOOST,
                                                   ^
vendor/qcom/opensource/power/../../../../device/xiaomi/miatoll/power/mode-ext.cpp:66:72: error: use of undeclared identifier 'LAUNCH_BOOST_V1'
                                                   kMaxLaunchDuration, LAUNCH_BOOST_V1);
                                                                       ^
vendor/qcom/opensource/power/../../../../device/xiaomi/miatoll/power/mode-ext.cpp:67:14: error: use of undeclared identifier 'CHECK_HANDLE'
        if (!CHECK_HANDLE(launch_handle)) {
             ^
4 errors generated.